// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuanLySinhVien.DataAccess.Data;

#nullable disable

namespace QuanLySinhVien.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260826112404_HocKy")]
    partial class HocKy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuanLySinhVien.Models.HocKy", b =>
                {
                    b.Property<int>("MaHocKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaHocKy"));

                    b.Property<DateTime>("NamHoc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenHocKy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaHocKy");

                    b.ToTable("hocKys");
                });

            modelBuilder.Entity("QuanLySinhVien.Models.Khoa", b =>
                {
                    b.Property<int>("MaKhoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaKhoa"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaKhoa");

                    b.ToTable("khoas");

                    b.HasData(
                        new
                        {
                            MaKhoa = 1,
                            MoTa = "Khoa công nghệ thông tin",
                            TenKhoa = "Hạ tầng kỹ thuật"
                        });
                });

            modelBuilder.Entity("QuanLySinhVien.Models.Lop", b =>
                {
                    b.Property<int>("MaLop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaLop"));

                    b.Property<int>("MaKhoa")
                        .HasColumnType("integer");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaLop");

                    b.HasIndex("MaKhoa");

                    b.ToTable("lops");
                });

            modelBuilder.Entity("QuanLySinhVien.Models.MonHoc", b =>
                {
                    b.Property<int>("MaMonHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaMonHoc"));

                    b.Property<int>("MaKhoa")
                        .HasColumnType("integer");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SoTinChi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenMonHoc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaMonHoc");

                    b.HasIndex("MaKhoa");

                    b.ToTable("monHocs");
                });

            modelBuilder.Entity("QuanLySinhVien.Models.SinhVien", b =>
                {
                    b.Property<int>("MaSinhVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaSinhVien"));

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("text");

                    b.Property<string>("CanCuocCongDan")
                        .HasColumnType("text");

                    b.Property<string>("DiaChi")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool?>("GioiTinh")
                        .HasColumnType("boolean");

                    b.Property<string>("Hoten")
                        .HasColumnType("text");

                    b.Property<int>("MaLop")
                        .HasColumnType("integer");

                    b.Property<string>("MaSoSinhVien")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayNhapHoc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("text");

                    b.HasKey("MaSinhVien");

                    b.HasIndex("MaLop");

                    b.ToTable("sinhViens");
                });

            modelBuilder.Entity("QuanLySinhVien.Models.Lop", b =>
                {
                    b.HasOne("QuanLySinhVien.Models.Khoa", "khoa")
                        .WithMany()
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("khoa");
                });

            modelBuilder.Entity("QuanLySinhVien.Models.MonHoc", b =>
                {
                    b.HasOne("QuanLySinhVien.Models.Khoa", "khoa")
                        .WithMany()
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("khoa");
                });

            modelBuilder.Entity("QuanLySinhVien.Models.SinhVien", b =>
                {
                    b.HasOne("QuanLySinhVien.Models.Lop", "Lop")
                        .WithMany()
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lop");
                });
#pragma warning restore 612, 618
        }
    }
}
