// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuanLySinhVien.DataAccess.Data;

#nullable disable

namespace QuanLySinhVien.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260826093514_Lop")]
    partial class Lop
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuanLySinhVien.Models.Khoa", b =>
                {
                    b.Property<int>("MaKhoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaKhoa"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaKhoa");

                    b.ToTable("khoas");

                    b.HasData(
                        new
                        {
                            MaKhoa = 1,
                            MoTa = "Khoa công nghệ thông tin",
                            TenKhoa = "Hạ tầng kỹ thuật"
                        });
                });

            modelBuilder.Entity("QuanLySinhVien.Models.Lop", b =>
                {
                    b.Property<int>("MaLop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaLop"));

                    b.Property<int>("MaKhoa")
                        .HasColumnType("integer");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaLop");

                    b.HasIndex("MaKhoa");

                    b.ToTable("lops");
                });

            modelBuilder.Entity("QuanLySinhVien.Models.Lop", b =>
                {
                    b.HasOne("QuanLySinhVien.Models.Khoa", "khoa")
                        .WithMany()
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("khoa");
                });
#pragma warning restore 612, 618
        }
    }
}
