// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuanLyDaoTao.DataAccess.Data;

#nullable disable

namespace QuanLyDaoTao.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260902131333_DiemDanh")]
    partial class DiemDanh
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("QuanLyDaoTao.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Hoten")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MaSinhVien")
                        .HasColumnType("integer");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("QuanLyDaoTao.Models.DangKyHocPhan", b =>
                {
                    b.Property<int>("MaDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaDangKy"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("MaHocKy")
                        .HasColumnType("integer");

                    b.Property<int>("MaHocPhan")
                        .HasColumnType("integer");

                    b.Property<int>("MaSinhVien")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("MaDangKy");

                    b.HasIndex("MaHocKy");

                    b.HasIndex("MaHocPhan");

                    b.HasIndex("MaSinhVien");

                    b.ToTable("dangKyHocPhans");
                });

            modelBuilder.Entity("QuanLyDaoTao.Models.Diem", b =>
                {
                    b.Property<int>("MaDiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaDiem"));

                    b.Property<decimal?>("DiemChuyenCan")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DiemCuoiKy")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DiemGiuaKy")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DiemNhanXet")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DiemTongKet")
                        .HasColumnType("numeric");

                    b.Property<string>("KetQua")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("MaDangKy")
                        .HasColumnType("integer");

                    b.HasKey("MaDiem");

                    b.HasIndex("MaDangKy");

                    b.ToTable("diems");
                });

            modelBuilder.Entity("QuanLyDaoTao.Models.DiemDanh", b =>
                {
                    b.Property<int>("MaDiemDanh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaDiemDanh"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<int>("MaLichHoc")
                        .HasColumnType("integer");

                    b.Property<int>("MaSinhVien")
                        .HasColumnType("integer");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("MaDiemDanh");

                    b.HasIndex("MaLichHoc");

                    b.HasIndex("MaSinhVien");

                    b.ToTable("diemDanhs");
                });

            modelBuilder.Entity("QuanLyDaoTao.Models.GiangVien", b =>
                {
                    b.Property<int>("MaGiangVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaGiangVien"));

                    b.Property<string>("ChucVu")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HocVi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("MaKhoa")
                        .HasColumnType("integer");

                    b.Property<string>("MaSoGiangVien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.HasKey("MaGiangVien");

                    b.HasIndex("MaKhoa");

                    b.ToTable("giangViens");
                });

            modelBuilder.Entity("QuanLyDaoTao.Models.HocKy", b =>
                {
                    b.Property<int>("MaHocKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaHocKy"));

                    b.Property<int>("NamHoc")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenHocKy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("MaHocKy");

                    b.ToTable("hocKys");

                    b.HasData(
                        new
                        {
                            MaHocKy = 1,
                            NamHoc = 2023,
                            NgayBatDau = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NgayKetThuc = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            TenHocKy = "Học kỳ 1"
                        });
                });

            modelBuilder.Entity("QuanLyDaoTao.Models.HocPhan", b =>
                {
                    b.Property<int>("MaHocPhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaHocPhan"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("MaGiangVien")
                        .HasColumnType("integer");

                    b.Property<int>("MaHocKy")
                        .HasColumnType("integer");

                    b.Property<string>("MaHocPhanCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("MaMonHoc")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayDongDangKy")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayMoDangKy")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SiSoHienTai")
                        .HasColumnType("integer");

                    b.Property<int>("SiSoToiDa")
                        .HasColumnType("integer");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("MaHocPhan");

                    b.HasIndex("MaGiangVien");

                    b.HasIndex("MaHocKy");

                    b.HasIndex("MaMonHoc");

                    b.ToTable("hocPhans");
                });

            modelBuilder.Entity("QuanLyDaoTao.Models.Khoa", b =>
                {
                    b.Property<int>("MaKhoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaKhoa"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("MaKhoa");

                    b.ToTable("khoas");

                    b.HasData(
                        new
                        {
                            MaKhoa = 1,
                            MoTa = "Khoa công nghệ thông tin",
                            TenKhoa = "Hạ tầng kỹ thuật"
                        });
                });

            modelBuilder.Entity("QuanLyDaoTao.Models.LichHoc", b =>
                {
                    b.Property<int>("MaLichHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaLichHoc"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("MaLop")
                        .HasColumnType("integer");

                    b.Property<int>("MaMonHoc")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SoTiet")
                        .HasColumnType("integer");

                    b.Property<int>("Thu")
                        .HasColumnType("integer");

                    b.Property<int>("TietBatDau")
                        .HasColumnType("integer");

                    b.HasKey("MaLichHoc");

                    b.HasIndex("MaLop");

                    b.HasIndex("MaMonHoc");

                    b.ToTable("lichHocs");
                });

            modelBuilder.Entity("QuanLyDaoTao.Models.Lop", b =>
                {
                    b.Property<int>("MaLop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaLop"));

                    b.Property<int>("MaKhoa")
                        .HasColumnType("integer");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("MaLop");

                    b.HasIndex("MaKhoa");

                    b.ToTable("lops");

                    b.HasData(
                        new
                        {
                            MaLop = 3,
                            MaKhoa = 1,
                            TenLop = "CNTT-K64"
                        });
                });

            modelBuilder.Entity("QuanLyDaoTao.Models.MonHoc", b =>
                {
                    b.Property<int>("MaMonHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaMonHoc"));

                    b.Property<int>("MaKhoa")
                        .HasColumnType("integer");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SoTinChi")
                        .HasColumnType("integer");

                    b.Property<string>("TenMonHoc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaMonHoc");

                    b.HasIndex("MaKhoa");

                    b.ToTable("monHocs");

                    b.HasData(
                        new
                        {
                            MaMonHoc = 1,
                            MaKhoa = 1,
                            MoTa = "Lập trình cơ bản trong python",
                            SoTinChi = 3,
                            TenMonHoc = "Lập trình cơ bản"
                        });
                });

            modelBuilder.Entity("QuanLyDaoTao.Models.PhongHoc", b =>
                {
                    b.Property<int>("MaPhongHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaPhongHoc"));

                    b.Property<int>("SucChua")
                        .HasColumnType("integer");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ToaNha")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.HasKey("MaPhongHoc");

                    b.ToTable("phongHocs");
                });

            modelBuilder.Entity("QuanLyDaoTao.Models.SinhVien", b =>
                {
                    b.Property<int>("MaSinhVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaSinhVien"));

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("text");

                    b.Property<string>("CanCuocCongDan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("boolean");

                    b.Property<string>("Hoten")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaLop")
                        .HasColumnType("integer");

                    b.Property<string>("MaSoSinhVien")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayNhapHoc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaSinhVien");

                    b.HasIndex("MaLop");

                    b.ToTable("sinhViens");

                    b.HasData(
                        new
                        {
                            MaSinhVien = 1,
                            AnhDaiDien = "an.jpg",
                            CanCuocCongDan = "079205001234",
                            DiaChi = "Đắk Lắk",
                            Email = "nguyenvanan@gmail.com",
                            GioiTinh = true,
                            Hoten = "Nguyễn Văn An",
                            MaLop = 3,
                            MaSoSinhVien = "SV001",
                            NgayNhapHoc = new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            NgaySinh = new DateTime(2005, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            SoDienThoai = "0901234567"
                        },
                        new
                        {
                            MaSinhVien = 2,
                            AnhDaiDien = "binh.jpg",
                            CanCuocCongDan = "079205002345",
                            DiaChi = "Gia Lai",
                            Email = "tranthibinh@gmail.com",
                            GioiTinh = false,
                            Hoten = "Trần Thị Bình",
                            MaLop = 3,
                            MaSoSinhVien = "SV002",
                            NgayNhapHoc = new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            NgaySinh = new DateTime(2005, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            SoDienThoai = "0912345678"
                        },
                        new
                        {
                            MaSinhVien = 3,
                            AnhDaiDien = "cuong.jpg",
                            CanCuocCongDan = "079204003456",
                            DiaChi = "Kon Tum",
                            Email = "levancuong@gmail.com",
                            GioiTinh = true,
                            Hoten = "Lê Văn Cường",
                            MaLop = 3,
                            MaSoSinhVien = "SV003",
                            NgayNhapHoc = new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            NgaySinh = new DateTime(2004, 11, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            SoDienThoai = "0923456789"
                        },
                        new
                        {
                            MaSinhVien = 4,
                            AnhDaiDien = "dung.jpg",
                            CanCuocCongDan = "079205004567",
                            DiaChi = "Đắk Nông",
                            Email = "phamthidung@gmail.com",
                            GioiTinh = false,
                            Hoten = "Phạm Thị Dung",
                            MaLop = 3,
                            MaSoSinhVien = "SV004",
                            NgayNhapHoc = new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            NgaySinh = new DateTime(2005, 6, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            SoDienThoai = "0934567890"
                        },
                        new
                        {
                            MaSinhVien = 5,
                            AnhDaiDien = "em.jpg",
                            CanCuocCongDan = "079205005678",
                            DiaChi = "Phú Yên",
                            Email = "hoangvanem@gmail.com",
                            GioiTinh = true,
                            Hoten = "Hoàng Văn Em",
                            MaLop = 3,
                            MaSoSinhVien = "SV005",
                            NgayNhapHoc = new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            NgaySinh = new DateTime(2005, 9, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            SoDienThoai = "0945678901"
                        });
                });

            modelBuilder.Entity("QuanLyDaoTao.Models.ThongBao", b =>
                {
                    b.Property<int>("MaThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaThongBao"));

                    b.Property<string>("LoaiNoiDung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("NgayDang")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayHetHan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiDang")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("MaThongBao");

                    b.ToTable("thongBaos");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("QuanLyDaoTao.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("QuanLyDaoTao.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyDaoTao.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("QuanLyDaoTao.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyDaoTao.Models.DangKyHocPhan", b =>
                {
                    b.HasOne("QuanLyDaoTao.Models.HocKy", "HocKy")
                        .WithMany()
                        .HasForeignKey("MaHocKy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyDaoTao.Models.HocPhan", "HocPhan")
                        .WithMany()
                        .HasForeignKey("MaHocPhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyDaoTao.Models.SinhVien", "SinhVien")
                        .WithMany()
                        .HasForeignKey("MaSinhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocKy");

                    b.Navigation("HocPhan");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("QuanLyDaoTao.Models.Diem", b =>
                {
                    b.HasOne("QuanLyDaoTao.Models.DangKyHocPhan", "DangKyHocPhan")
                        .WithMany()
                        .HasForeignKey("MaDangKy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DangKyHocPhan");
                });

            modelBuilder.Entity("QuanLyDaoTao.Models.DiemDanh", b =>
                {
                    b.HasOne("QuanLyDaoTao.Models.LichHoc", "LichHoc")
                        .WithMany()
                        .HasForeignKey("MaLichHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyDaoTao.Models.SinhVien", "SinhVien")
                        .WithMany()
                        .HasForeignKey("MaSinhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LichHoc");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("QuanLyDaoTao.Models.GiangVien", b =>
                {
                    b.HasOne("QuanLyDaoTao.Models.Khoa", "Khoa")
                        .WithMany()
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("QuanLyDaoTao.Models.HocPhan", b =>
                {
                    b.HasOne("QuanLyDaoTao.Models.GiangVien", "GiangVien")
                        .WithMany()
                        .HasForeignKey("MaGiangVien");

                    b.HasOne("QuanLyDaoTao.Models.HocKy", "HocKy")
                        .WithMany()
                        .HasForeignKey("MaHocKy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyDaoTao.Models.MonHoc", "MonHoc")
                        .WithMany()
                        .HasForeignKey("MaMonHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("HocKy");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("QuanLyDaoTao.Models.LichHoc", b =>
                {
                    b.HasOne("QuanLyDaoTao.Models.Lop", "Lop")
                        .WithMany()
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyDaoTao.Models.MonHoc", "MonHoc")
                        .WithMany()
                        .HasForeignKey("MaMonHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lop");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("QuanLyDaoTao.Models.Lop", b =>
                {
                    b.HasOne("QuanLyDaoTao.Models.Khoa", "Khoa")
                        .WithMany()
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("QuanLyDaoTao.Models.MonHoc", b =>
                {
                    b.HasOne("QuanLyDaoTao.Models.Khoa", "Khoa")
                        .WithMany()
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("QuanLyDaoTao.Models.SinhVien", b =>
                {
                    b.HasOne("QuanLyDaoTao.Models.Lop", "Lop")
                        .WithMany()
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lop");
                });
#pragma warning restore 612, 618
        }
    }
}
