// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuanLyDaoTao.DataAccess.Data;

#nullable disable

namespace QuanLyDaoTao.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260829102110_SeedSinhVien")]
    partial class SeedSinhVien
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuanLyDaoTao.Models.HocKy", b =>
                {
                    b.Property<int>("MaHocKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaHocKy"));

                    b.Property<int>("NamHoc")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenHocKy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaHocKy");

                    b.ToTable("hocKys");
                });

            modelBuilder.Entity("QuanLyDaoTao.Models.Khoa", b =>
                {
                    b.Property<int>("MaKhoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaKhoa"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("MaKhoa");

                    b.ToTable("khoas");

                    b.HasData(
                        new
                        {
                            MaKhoa = 1,
                            MoTa = "Khoa công nghệ thông tin",
                            TenKhoa = "Hạ tầng kỹ thuật"
                        });
                });

            modelBuilder.Entity("QuanLyDaoTao.Models.Lop", b =>
                {
                    b.Property<int>("MaLop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaLop"));

                    b.Property<int>("MaKhoa")
                        .HasColumnType("integer");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("MaLop");

                    b.HasIndex("MaKhoa");

                    b.ToTable("lops");
                });

            modelBuilder.Entity("QuanLyDaoTao.Models.MonHoc", b =>
                {
                    b.Property<int>("MaMonHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaMonHoc"));

                    b.Property<int>("MaKhoa")
                        .HasColumnType("integer");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SoTinChi")
                        .HasColumnType("integer");

                    b.Property<string>("TenMonHoc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaMonHoc");

                    b.HasIndex("MaKhoa");

                    b.ToTable("monHocs");
                });

            modelBuilder.Entity("QuanLyDaoTao.Models.SinhVien", b =>
                {
                    b.Property<int>("MaSinhVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaSinhVien"));

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("text");

                    b.Property<string>("CanCuocCongDan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("boolean");

                    b.Property<string>("Hoten")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaLop")
                        .HasColumnType("integer");

                    b.Property<string>("MaSoSinhVien")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayNhapHoc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaSinhVien");

                    b.HasIndex("MaLop");

                    b.ToTable("sinhViens");

                    b.HasData(
                        new
                        {
                            MaSinhVien = 1,
                            AnhDaiDien = "an.jpg",
                            CanCuocCongDan = "079205001234",
                            DiaChi = "Đắk Lắk",
                            Email = "nguyenvanan@gmail.com",
                            GioiTinh = true,
                            Hoten = "Nguyễn Văn An",
                            MaLop = 3,
                            MaSoSinhVien = "SV001",
                            NgayNhapHoc = new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            NgaySinh = new DateTime(2005, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            SoDienThoai = "0901234567"
                        },
                        new
                        {
                            MaSinhVien = 2,
                            AnhDaiDien = "binh.jpg",
                            CanCuocCongDan = "079205002345",
                            DiaChi = "Gia Lai",
                            Email = "tranthibinh@gmail.com",
                            GioiTinh = false,
                            Hoten = "Trần Thị Bình",
                            MaLop = 3,
                            MaSoSinhVien = "SV002",
                            NgayNhapHoc = new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            NgaySinh = new DateTime(2005, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            SoDienThoai = "0912345678"
                        },
                        new
                        {
                            MaSinhVien = 3,
                            AnhDaiDien = "cuong.jpg",
                            CanCuocCongDan = "079204003456",
                            DiaChi = "Kon Tum",
                            Email = "levancuong@gmail.com",
                            GioiTinh = true,
                            Hoten = "Lê Văn Cường",
                            MaLop = 3,
                            MaSoSinhVien = "SV003",
                            NgayNhapHoc = new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            NgaySinh = new DateTime(2004, 11, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            SoDienThoai = "0923456789"
                        },
                        new
                        {
                            MaSinhVien = 4,
                            AnhDaiDien = "dung.jpg",
                            CanCuocCongDan = "079205004567",
                            DiaChi = "Đắk Nông",
                            Email = "phamthidung@gmail.com",
                            GioiTinh = false,
                            Hoten = "Phạm Thị Dung",
                            MaLop = 3,
                            MaSoSinhVien = "SV004",
                            NgayNhapHoc = new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            NgaySinh = new DateTime(2005, 6, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            SoDienThoai = "0934567890"
                        },
                        new
                        {
                            MaSinhVien = 5,
                            AnhDaiDien = "em.jpg",
                            CanCuocCongDan = "079205005678",
                            DiaChi = "Phú Yên",
                            Email = "hoangvanem@gmail.com",
                            GioiTinh = true,
                            Hoten = "Hoàng Văn Em",
                            MaLop = 3,
                            MaSoSinhVien = "SV005",
                            NgayNhapHoc = new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            NgaySinh = new DateTime(2005, 9, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            SoDienThoai = "0945678901"
                        });
                });

            modelBuilder.Entity("QuanLyDaoTao.Models.Lop", b =>
                {
                    b.HasOne("QuanLyDaoTao.Models.Khoa", "Khoa")
                        .WithMany()
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("QuanLyDaoTao.Models.MonHoc", b =>
                {
                    b.HasOne("QuanLyDaoTao.Models.Khoa", "Khoa")
                        .WithMany()
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("QuanLyDaoTao.Models.SinhVien", b =>
                {
                    b.HasOne("QuanLyDaoTao.Models.Lop", "Lop")
                        .WithMany()
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lop");
                });
#pragma warning restore 612, 618
        }
    }
}
